const bcrypt = require('bcryptjs');

const hashFromSeed = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5lW7QK5n8jLGG';
const password = 'Password@123';

console.log('Testing hash from seed.sql...');
bcrypt.compare(password, hashFromSeed, (err, res) => {
    if (err) {
        console.error('Error comparing:', err);
    } else {
        console.log('Comparison result:', res);
    }
});

const newHash = bcrypt.hashSync(password, 12);
console.log('New hash generated by bcryptjs:', newHash);
